"""add_ton_wallet_and_inventory_uniqueness

Revision ID: 5d022416d673
Revises: f9a0b1c2d3e4
Create Date: 2026-03-21 01:52:30.693250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d022416d673'
down_revision = 'f9a0b1c2d3e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_user_item', 'inventory', ['user_id', 'item_type', 'item_id'])
    op.add_column('users', sa.Column('wallet_address', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('wallet_connected_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_column('users', 'wallet_connected_at')
    op.drop_column('users', 'wallet_address')
    op.drop_constraint('uq_inventory_user_item', 'inventory', type_='unique')
    # ### end Alembic commands ###
