"""add admin_notified_at to userbot_gift_orders

Revision ID: fc1c4dc7bf8c
Revises: d8e9f0a1b2c3
Create Date: 2026-04-19 01:08:03.383780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1c4dc7bf8c'
down_revision = 'd8e9f0a1b2c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stats', 'daily_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('userbot_gift_orders', sa.Column('admin_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'login_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('userbot_gift_orders', 'admin_notified_at')
    op.alter_column('user_stats', 'daily_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
